name: pandas-checks

# CINTENT >> MANUAL TRIGGER
# on:
#   schedule:
#     - cron: '0 0 1 * *'
#   push:
#     branches:
#       - main
#       - master
#   pull_request:
#     branches:
#       - main
#       - master
on: [repository_dispatch, workflow_dispatch]


jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        config:
          # - { os: ubuntu-latest, python-version: '3.9', pandas-version: '1.5.0' }

          # CINTENT >> REMOVE_MATRIX
          # - { os: ubuntu-latest, python-version: '3.9', pandas-version: '2.2.0' }

          - { os: ubuntu-latest, python-version: '3.11', pandas-version: 'latest' }

    defaults:
      run:
        shell: bash

    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.python-version }}) - pandas ${{ matrix.config.pandas-version }}

    steps:
      - name: Set up Python Version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.config.python-version }}

      - name: Check-out repository
        uses: actions/checkout@v4

      # CINTENT >> INSERT_CINTENT
      - uses: JavidDitty/setup-cintent@a606c80c34ec190c6a20dea33d6d58ddb6c4e0cc

      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install package
        run: |
          poetry install
          if [ "${{ matrix.config.pandas-version }}" == "latest" ]; then
            poetry add pandas@latest
          else
            poetry add pandas==${{ matrix.config.pandas-version }}
          fi
      
      - run: |
          source $VENV
          pytest --version

      - name: Test with pytest
        run: poetry run pytest tests/ --verbose

      # CINTENT >> INSERT_CINTENT
      - name: Upload CIntent Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ env.CINTENT_ARTIFACT_NAME }}
          path: ${{ env.CINTENT_LOGS }}
